### ISSUE TITLE
src/interp3.cpp:5:32: error: ‘__m256 _mm256_insertf128_ps’ redeclared as different kind of entity

### ISSUE THREAD

**Issue by andreasmang** [andreasmang/claire#10]
original post can be found here: https://github.com/andreasmang/claire/issues/9#issuecomment-837101502

**Comment by andreasmang** [comment]
**with** `gcc` (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 and `avx insructions` (probably) Intel® Core™ i9-9880H CPU @ 2.30GHz × 16


I tried a fresh install, setting USEPNETCDF=no as you suggested. This eliminate the error, but I still have no binaries (and no bin directory either). The output of "make -j" (and of "make -j 12") is as follows.

```bash
fatal: not a git repository (or any of the parent directories): .git
mpicxx -O3 -ansi -fopenmp -march=native -std=c++11 -Warray-bounds -Wchar-subscripts -Wcomment -Wenum-compare -Wformat -Wuninitialized -Wmaybe-uninitialized -Wmain -Wnarrowing -Wnonnull -Wparentheses -Wreorder -Wreturn-type -Wsign-compare -Wsequence-point -Wtrigraphs -Wunused-function -Wwrite-strings -DGIT_VERSION="" -I./include -isystem/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/include -isystem/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/cxx_opt_dbl/include -I/home/asaki/Software/claire-cpu/deps/libs/accfft/build/include -I/home/asaki/Software/claire-cpu/deps/libs/fftw/build/include -I/home/asaki/Software/claire-cpu/deps/libs/libmorton -I./deps/3rdparty -c apps/claire.cpp -o obj/claire.o
mpicxx -O3 -ansi -fopenmp -march=native -std=c++11 -Warray-bounds -Wchar-subscripts -Wcomment -Wenum-compare -Wformat -Wuninitialized -Wmaybe-uninitialized -Wmain -Wnarrowing -Wnonnull -Wparentheses -Wreorder -Wreturn-type -Wsign-compare -Wsequence-point -Wtrigraphs -Wunused-function -Wwrite-strings -DGIT_VERSION="" -I./include -isystem/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/include -isystem/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/cxx_opt_dbl/include -I/home/asaki/Software/claire-cpu/deps/libs/accfft/build/include -I/home/asaki/Software/claire-cpu/deps/libs/fftw/build/include -I/home/asaki/Software/claire-cpu/deps/libs/libmorton -I./deps/3rdparty -c src/interp3.cpp -o obj/interp3.o
src/interp3.cpp:5:11: warning: ‘_mm256_insertf128_ps’ initialized and declared ‘extern’
5 | _mm256_insertf128_ps(_mm256_castps128_ps256(vb), va, 1)
| ^~~~~~~~~~~~~~~~~~~~
src/interp3.cpp:5:32: warning: ‘gnu_inline’ attribute ignored [-Wattributes]
5 | _mm256_insertf128_ps(_mm256_castps128_ps256(vb), va, 1)
| ^~~~~~~~~~~~~~~~~~~~~~
src/interp3.cpp:5:32: warning: ‘always_inline’ attribute ignored [-Wattributes]
src/interp3.cpp:5:32: warning: ‘artificial’ attribute ignored [-Wattributes]
src/interp3.cpp:5:32: error: ‘__m256 _mm256_insertf128_ps’ redeclared as different kind of entity
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/immintrin.h:51,
from src/interp3.cpp:16:
/usr/lib/gcc/x86_64-linux-gnu/9/include/avxintrin.h:760:1: note: previous declaration ‘__m256 _mm256_insertf128_ps(__m256, __m128, int)’
760 | _mm256_insertf128_ps (__m256 __X, __m128 __Y, const int __O)
| ^~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/9/include/avxintrin.h:1489:1: error: expected primary-expression before ‘__L’
1489 | _mm256_set_m128 ( __m128 __H, __m128 __L)
| ^~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/9/include/avxintrin.h:1489:1: error: expected primary-expression before ‘__H’
1489 | _mm256_set_m128 ( __m128 __H, __m128 __L)
| ^~~~~~~~~~~~~~~
make: *** [makefile:25: obj/interp3.o] Error 1
rm obj/claire.o"
```

**Comment by naveenaero** [comment]
I am working on this issue. It will take some more time. In the meanwhile can you try a lower version of GCC if you have available, say <7?

**Comment by tjasaki** [comment]
Using gcc 7 (earliest I could quickly find) leads to the following result.  A bin directory is created but remains empty.

fatal: not a git repository (or any of the parent directories): .git
mpicxx             -O3 -ansi -fopenmp -march=native -std=c++11 -Warray-bounds -Wchar-subscripts -Wcomment -Wenum-compare -Wformat -Wuninitialized -Wmaybe-uninitialized -Wmain -Wnarrowing -Wnonnull -Wparentheses  -Wreorder -Wreturn-type -Wsign-compare -Wsequence-point -Wtrigraphs -Wunused-function -Wwrite-strings  -DGIT_VERSION=\"\" -I./include -isystem/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/include -isystem/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/cxx_opt_dbl/include -I/home/asaki/Software/claire-cpu/deps/libs/accfft/build/include -I/home/asaki/Software/claire-cpu/deps/libs/fftw/build/include -I/home/asaki/Software/claire-cpu/deps/libs/libmorton -I./deps/3rdparty -c apps/claire.cpp -o obj/claire.o
mpicxx             -O3 -ansi -fopenmp -march=native -std=c++11 -Warray-bounds -Wchar-subscripts -Wcomment -Wenum-compare -Wformat -Wuninitialized -Wmaybe-uninitialized -Wmain -Wnarrowing -Wnonnull -Wparentheses  -Wreorder -Wreturn-type -Wsign-compare -Wsequence-point -Wtrigraphs -Wunused-function -Wwrite-strings  -DGIT_VERSION=\"\" -I./include -isystem/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/include -isystem/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/cxx_opt_dbl/include -I/home/asaki/Software/claire-cpu/deps/libs/accfft/build/include -I/home/asaki/Software/claire-cpu/deps/libs/fftw/build/include -I/home/asaki/Software/claire-cpu/deps/libs/libmorton -I./deps/3rdparty obj/claire.o obj/RegOpt.o obj/RegToolsOpt.o obj/BenchmarkOpt.o obj/CLAIREUtils.o obj/ghost.o obj/interp3.o obj/Interp3_Plan.o obj/VecField.o obj/TenField.o obj/ReadWriteReg.o obj/SynProbRegistration.o obj/DeformationFields.o obj/DistanceMeasure.o obj/DistanceMeasureNCC.o obj/DistanceMeasureSL2.o obj/DistanceMeasureSL2aux.o obj/SemiLagrangian.o obj/Optimizer.o obj/KrylovInterface.o obj/TaoInterface.o obj/CLAIREInterface.o obj/MultiLevelPyramid.o obj/Preconditioner.o obj/Regularization.o obj/RegularizationL2.o obj/RegularizationH1.o obj/RegularizationH2.o obj/RegularizationH1SN.o obj/RegularizationH2SN.o obj/RegularizationH3.o obj/RegularizationH3SN.o obj/OptimizationProblem.o obj/CLAIREBase.o obj/CLAIRE.o obj/CLAIREStokes.o obj/CLAIREDivReg.o obj/Preprocessing.o -L/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/lib -L/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/cxx_opt_dbl/lib -lpetsc -lf2clapack -lf2cblas  -ldl -lm -L/home/asaki/Software/claire-cpu/deps/libs/accfft/build/lib -laccfft -laccfft_utils -L/home/asaki/Software/claire-cpu/deps/libs/fftw/build/lib -lfftw3_threads -lfftw3  -o bin/claire
/usr/bin/ld: cannot find -lpetsc
collect2: error: ld returned 1 exit status
make: *** [makefile:21: bin/claire] Error 1
rm obj/claire.o

**Comment by naveenaero** [comment]
okay, so its not finding the petsc libraries. Can you check the following path is present in your LD_LIBRARY_PATH? If not then prepend it please.

/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/lib

and whether it contains the libpetsc.so files?

**Comment by tjasaki** [comment]
The directory 

/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build

contains two subdirectories:

cxx_opt_dbl
cxx_opt_sgl

This branch of the directory tree nowhere contains the file libpetsc.so

The path variable looks like this:

asaki@idaho:~/Software/claire-cpu$ $LD_LIBRARY_PATH
bash: /home/asaki/Software/claire-cpu/deps/libs/zlib/build/lib:/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/cxx_dbg_sgl/lib:/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/cxx_dbg_dbl/lib:/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/cxx_opt_sgl/lib:/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/cxx_opt_dbl/lib:/home/asaki/Software/claire-cpu/deps/libs/fftw/build/lib:: No such file or directory

The cxx_opt_sgl/lib subdirectory contains the following directory tree structure:

asaki@idaho:~/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/cxx_opt_sgl/lib$ ls -R
.:
libf2cblas.a  libf2clapack.a  petsc  pkgconfig

./petsc:
bin  conf

./petsc/bin:
PetscBinaryIO.py            petsc_conf.py      petsclogformat.py   saws
PetscBinaryIO_tests.py      petscdiff          petscmpiexec        taucc.py
PetscBinaryIOTrajectory.py  petsc_gen_xdmf.py  petscnagupgrade.py

./petsc/bin/saws:
getSAWs.bash  getStack.bash  SAWs.py

./petsc/conf:
modules                   petscvariables              rules         variables
PETScBuildInternal.cmake  pkg.conf.f2cblaslapack      test
petscrules                reconfigure-cxx_opt_sgl.py  uninstall.py

./petsc/conf/modules:
petsc

./petsc/conf/modules/petsc:
3.9.1

./pkgconfig:
PETSc.pc

**Comment by andreasmang** [comment]
@tjasaki: The lib folder should contain `libpetsc.a`:

```bash
[amang@opuntia lib]$ ll
total 51500
-rw-rw-r-- 1 amang mang  1171724 Apr 15 11:01 libf2cblas.a
-rw-rw-r-- 1 amang mang 11851592 Apr 15 11:01 libf2clapack.a
-rw-rw-r-- 1 amang mang 39705230 Apr 15 11:02 libpetsc.a
drwxrwxr-x 4 amang mang       29 Apr 15 11:02 petsc
drwxrwxr-x 2 amang mang       22 Apr 15 11:01 pkgconfig
```

in 

```bash
[amang@opuntia lib]$ pwd -P
/home/amang/code/claire/deps/libs/petsc-lite-3.9.1/build/cxx_opt_sgl/lib
```

I suspect PETSc did exit with an error. Can you delete the PETSc folder (~/Software/claire-cpu/deps/libs/petsc-lite-3.9.1) and recompile PETSc on its own?

I suppose you want single precision, correct? Then it would be:
```bash
./build_libs.sh --bpetscsgl
 ```
 
If you want double precision:
```bash
./build_libs.sh --bpetscdbl
 ```
 
 Can you share the log file if there is an error message during the compilation of PETSc?

**Comment by tjasaki** [comment]
I removed the directory and compiled as suggested.  And yes, there is an error during the compile.  The message (embeded in the terminal output is:

----- cut -----
[lots of stuff before this]
make[1]: *** [/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/src/lib/petsc/conf/rules:81: gnumake] Error 2
make[1]: Leaving directory '/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/src'
**************************ERROR*************************************
  Error during compile, check cxx_opt_sgl/lib/petsc/conf/make.log
  Send it and cxx_opt_sgl/lib/petsc/conf/configure.log to petsc-maint@mcs.anl.gov
********************************************************************
make: *** [makefile:36: all] Error 1
*** Using PETSC_DIR=/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/src PETSC_ARCH=cxx_opt_sgl ***
*** Installing PETSc at prefix location: /home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/cxx_opt_sgl  ***
====================================
Install complete.
Now to check if the libraries are working do (in current directory):
make PETSC_DIR=/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/build/cxx_opt_sgl PETSC_ARCH="" test
====================================
/usr/bin/make  --no-print-directory PETSC_ARCH=cxx_opt_sgl PETSC_DIR=/home/asaki/Software/claire-cpu/deps/libs/petsc-lite-3.9.1/src mpi4py-install petsc4py-install libmesh-install slepc-install
make[1]: Nothing to be done for 'mpi4py-install'.
make[1]: Nothing to be done for 'petsc4py-install'.
make[1]: Nothing to be done for 'libmesh-install'.
make[1]: Nothing to be done for 'slepc-install'.

The two log files (make.log and configure.log) do not exist in the specified locations.

**Comment by andreasmang** [comment]
@tjasaki This output is difficult to interpret (at least for me). Can you send me the full output in your command window (since you state that the make.log files do not exist)? I'll see if I can figure it out. [ andreas@math.uh.edu ]

I'm blocked today but I might have time tomorrow.

**Comment by andreasmang** [comment]
You can check the src directory. The log files might be there:

```bash
[amang@opuntia src]$ ll
total 9732
-rw-rw-r--  1 amang mang     262 Apr 15 11:02 buildsystem.log
-rw-------  1 amang mang   69154 Apr 15 11:01 CMakeLists.txt
drwxr-xr-x  5 amang mang    4096 Apr 15 11:01 config
-rwxr-xr-x  1 amang mang     662 Apr  7  2018 configure
lrwxrwxrwx  1 amang mang      40 Apr 15 11:01 configure.log -> cxx_opt_sgl/lib/petsc/conf/configure.log
-rw-r--r--  1 amang mang    1751 Mar 24  2018 CONTRIBUTING
-rw-r--r--  1 amang mang 6175082 Apr 29  2018 CTAGS
drwxrwxr-x  9 amang mang     206 Apr 15 11:01 cxx_opt_sgl
-rw-r--r--  1 amang mang    8807 Apr  7  2018 gmakefile
-rw-r--r--  1 amang mang   13364 Apr 29  2018 gmakefile.test
drwxr-xr-x  3 amang mang    4096 Apr 29  2018 include
drwxr-xr-x  3 amang mang      33 Apr 29  2018 interfaces
drwxr-xr-x  3 amang mang      19 May 15  2016 lib
-rw-r--r--  1 amang mang    1526 Mar 24  2018 LICENSE
-rw-r--r--  1 amang mang   29724 Apr 29  2018 makefile
lrwxrwxrwx  1 amang mang      35 Apr 15 11:01 make.log -> cxx_opt_sgl/lib/petsc/conf/make.log
-rw-r--r--  1 amang mang    1900 Apr 29  2018 PKG-INFO
-rw-rw-r--  1 amang mang 1483725 Apr 15 11:02 RDict.log
-rwxr-xr-x  1 amang mang    9435 Apr  7  2018 setup.py
drwxr-xr-x  3 amang mang      19 May 13  2013 share
drwxr-xr-x 12 amang mang     142 Apr 29  2018 src
drwxr-xr-x  3 amang mang      19 May 13  2013 systems
-rw-r--r--  1 amang mang 2128114 Apr 29  2018 TAGS
```

where:

```bash
[amang@opuntia src]$ pwd -P
/home/amang/code/claire/deps/libs/petsc-lite-3.9.1/src
```

**Comment by tjasaki** [comment]
Yes.  See attached.  Wow, configure.log is unexpectedly large.
[make.log](https://github.com/andreasmang/claire/files/6461633/make.log)
[configure.log](https://github.com/andreasmang/claire/files/6461638/configure.log)

**Comment by andreasmang** [comment]
Seems to be related to this:

https://github.com/sigvaldm/arch-fenics-packages/issues/1

It configures fine. The make step chokes with MPI errors (it seems). Which GCC and MPI are you using? 

I'll see if I can either mimic this on our system and/or if we can move to a newer version of PETSc (that compiles on my local system). Again, not much time today but I'll look into it once I have some...

**Comment by naveenaero** [comment]
I can look into it as well, if you can tell which MPI are you using?

**Comment by tjasaki** [comment]
GCC Information:

gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0 
(I also tried 9.x)



MPI information:

                 Package: Debian OpenMPI
                Open MPI: 4.0.3
  Open MPI repo revision: v4.0.3
   Open MPI release date: Mar 03, 2020
                Open RTE: 4.0.3
  Open RTE repo revision: v4.0.3
   Open RTE release date: Mar 03, 2020
                    OPAL: 4.0.3
      OPAL repo revision: v4.0.3
       OPAL release date: Mar 03, 2020
                 MPI API: 3.1.0
            Ident string: 4.0.3
                  Prefix: /usr
 Configured architecture: x86_64-pc-linux-gnu

**Comment by naveenaero** [comment]
I am trying to recreate the issue on my side. I will post updates once I have something.

**Comment by naveenaero** [comment]
Turns out petsc 3.9.1 doesn't work with OpenMPI 4.0.3. 
I have pushed a fix for this. You will need to again do:

```bash
cd deps/
./get_libs.sh #to get the newer version of petsc 3.11.4)
./build_libs.sh --bpetscsgl
```

and then try to recompile for single precision.

**Comment by andreasmang** [comment]
Everything also compiles on our end (using the old compilers). About to push a fix for the makefile (I introduced an issue when I added some documentation).

**Comment by tjasaki** [comment]
Thanks much!  I did need a complete reinstall (after ineffectively correcting a handful of old directory variables and references.  But now claire is up and running fine.

**Comment by naveenaero** [comment]
Awesome! We will take all possible feedback from this and make the installation process smoother.

**Comment by andreasmang** [comment]
@tjasaki Thanks for your patience. I'll close this and look forward to additional suggestions. I made a note here about the `avx` compilation error. We'll look into it:

https://github.com/andreasmang/claire/blob/cpu/doc/README-INSTALL.md#troubleshooting-
